# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.CharField(max_length=500),
        ),
    ]
