# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-30 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isNew',
            field=models.BooleanField(),
        ),
    ]
