# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='username',
            new_name='user',
        ),
    ]
