# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('files', models.ManyToManyField(related_name='files', to='newsletter.Report')),
            ],
        ),
    ]
