# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='report',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.FileField(default='blank/', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
