# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='projects',
            field=models.TextField(default='project', max_length=300),
        ),
    ]
