# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170409_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='report',
            name='projects',
            field=models.CharField(default='project', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.FileField(blank=True, upload_to='reports/'),
        ),
    ]
