# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170418_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='group',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.ManyToManyField(default='none', to='newsletter.File'),
        ),
    ]
